### ISSUE TITLE
tern-find-definition doesn't work in attributes

### ISSUE THREAD

**Issue by shevchuk** [jacksonrayhamilton/tern-jsx#5]
If I perform `tern-find-definition` on `LABEL` it works:

```
<label>{params.LABEL}</label>
```

If I perform `tern-find-definition` on `LABEL` it doesn't work:
```
<label label={params.LABEL}></label>
```

Looks like attributes parsing is not working properly.

**Comment by jacksonrayhamilton** [comment]
Hi @shevchuk, sorry, I forgot about this.  Is this still an issue for you?  I tried to reproduce in Emacs, and am able to jump to the definition in this file:

```jsx
var params = {
  LABEL: 1
};

var a = <label foo={params.LABEL}></label>;
```

At point 53 (start of `params.LABEL`) it takes me to point 5 (definition of variable `params`), and at point 60 (start of accessing the property `LABEL`) it takes me to point 18 (definition of property `LABEL`).

Emacs: 25.1.1
Tern Emacs: 20161222.850
tern npm: 0.21
tern-jsx: 1.0.2

**Comment by shevchuk** [comment]
It Works, thanks!
