### ISSUE TITLE
update to tern 0.21.0

### ISSUE THREAD

**Issue by cooperc0** [jacksonrayhamilton/tern-jsx#6]
Tern is now at v0.21.0. tern-jsx doesn't seem to have any issues with the newer version, but npm complains about the version discrepancy since ^0.20.0 is a peer dependency.

**Comment by jacksonrayhamilton** [comment]
1.0.3 is released and bumps the Tern version to 0.21.  Thanks for testing and confirming there were no compatibility issues.
